name:                distributed-process-task-queue
version:             0.1.0.0
github:              "advancedtelematic/distributed-process-task-queue"
license:             BSD3
author:              "Robert Danitz"
maintainer:          "robert.danitz@here.com"
copyright:           "Copyright (C) 2018, HERE Europe B.V."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Distributed Computing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/advancedtelematic/distributed-process-task-queue#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- distributed-process
- mtl
- quickcheck-state-machine-distributed

library:
  source-dirs: src

tests:
  distributed-process-task-queue-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distributed-process-task-queue
